
import React, { useEffect } from 'react';
import { Link } from 'react-router-dom';
import { Button } from '@/components/ui/button';
import { ArrowLeft } from 'lucide-react';
import { motion } from 'framer-motion';

export const PrivacyPage = () => {
  // Scroll to top on mount
  useEffect(() => {
    window.scrollTo(0, 0);
  }, []);

  return (
    <div className="min-h-screen bg-[#101112] text-white font-sans selection:bg-purple-500/30">
      {/* Navigation */}
      <nav className="fixed w-full z-50 bg-[#101112]/50 backdrop-blur-lg border-b border-white/10">
        <div className="container mx-auto px-4 h-16 flex items-center justify-between">
          <Link to="/" className="flex items-center gap-2">
            <img
              src="/assets/akita-logo.png"
              alt="Akitá Logo"
              className="h-8 w-auto mr-2 opacity-90"
            />
            <span className="text-xl font-bold bg-gradient-to-r from-purple-400 via-pink-500 to-red-500 bg-clip-text text-transparent">
              PictureMe
            </span>
          </Link>
          <Link to="/">
            <Button variant="ghost" size="sm" className="gap-2">
              <ArrowLeft className="w-4 h-4" />
              Back to Home
            </Button>
          </Link>
        </div>
      </nav>

      <main className="container mx-auto px-4 py-24 max-w-4xl">
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          className="space-y-8"
        >
          {/* Header */}
          <div className="text-center space-y-4 mb-12">
            <h1 className="text-4xl md:text-5xl font-bold bg-gradient-to-r from-purple-400 via-pink-500 to-red-500 bg-clip-text text-transparent pb-2">
              Privacy Policy
            </h1>
            <div className="text-gray-400 text-lg">
              PictureMe – AI Generative Platform & Photobooth
              <br />
              Operated by Akitá LLC
            </div>
            <p className="text-sm text-gray-500">Updated: 2025</p>
          </div>

          {/* Introduction */}
          <div className="bg-card/50 border border-white/10 rounded-2xl p-8 backdrop-blur-sm">
            <p className="text-gray-300 leading-relaxed">
              Your privacy is important to us. This Privacy Policy explains how PictureMe ("we", "our", "Akitá LLC") collects, uses, stores, and protects your information when you use our AI generative platform and photobooth services.
            </p>
          </div>

          {/* Sections */}
          <div className="space-y-8 text-gray-300">
            <Section number="1" title="Information We Collect">
              <p>We may collect the following types of information:</p>

              <div className="mt-4 space-y-4">
                <div>
                  <h3 className="text-white font-semibold text-lg mb-2">1.1 User-Provided Information</h3>
                  <ul className="list-disc pl-6 space-y-2">
                    <li>Names, email addresses, or contact details provided during account creation or event participation.</li>
                    <li>Images uploaded, captured, or generated by the platform.</li>
                    <li>Prompts, instructions, or text entered into the system.</li>
                  </ul>
                </div>

                <div>
                  <h3 className="text-white font-semibold text-lg mb-2">1.2 Automatic System Data</h3>
                  <ul className="list-disc pl-6 space-y-2">
                    <li>Device type, browser type, IP address, and basic technical metadata.</li>
                    <li>Event usage patterns, generation logs, and consumption of tokens.</li>
                    <li>Cookies or tracking identifiers for platform functionality and analytics.</li>
                  </ul>
                </div>
              </div>
            </Section>

            <Section number="2" title="How We Use Your Information">
              <p>Your information may be used to:</p>
              <ul className="list-disc pl-6 space-y-2 mt-2">
                <li>Generate images or visual content using AI models.</li>
                <li>Provide access to your photo albums, event galleries, or purchased content.</li>
                <li>Improve platform performance, stability, and user experience.</li>
                <li>Send transactional emails and event-related messages (verification, delivery, receipts).</li>
                <li>Provide customer support and resolve technical issues.</li>
                <li>Prevent fraud, abuse, or misuse of the platform.</li>
              </ul>
              <p className="mt-4 font-medium text-white/90">
                We do not sell your personal information to third parties.
              </p>
            </Section>

            <Section number="3" title="Storage & Retention of Photos">
              <ul className="list-disc pl-6 space-y-2">
                <li>Photos are stored temporarily to allow viewing, downloading, or sharing.</li>
                <li>Storage duration may vary depending on your event settings or account type.</li>
                <li>Business/event hosts are responsible for obtaining consent from participants.</li>
                <li>We do not use event photos for training AI models unless explicitly permitted.</li>
              </ul>
            </Section>

            <Section number="4" title="Data Sharing">
              <p>We may share limited data with:</p>
              <ul className="list-disc pl-6 space-y-2 mt-2">
                <li>Service providers (e.g., AWS, email providers) strictly for operational purposes.</li>
                <li>Event organizers who manage their own galleries or attendees.</li>
                <li>Legal authorities if required to comply with law or protect platform integrity.</li>
              </ul>
              <p className="mt-4 font-medium text-white/90">
                We do not share or disclose your data for advertising or marketing without consent.
              </p>
            </Section>

            <Section number="5" title="User-Generated Content Responsibilities">
              <p>You are responsible for:</p>
              <ul className="list-disc pl-6 space-y-2 mt-2">
                <li>Ensuring you have permission to upload or submit images.</li>
                <li>Avoiding content that is illegal, harmful, or violates privacy rights.</li>
                <li>Complying with local regulations regarding image capture and disclosure.</li>
              </ul>
            </Section>

            <Section number="6" title="Security">
              <p>Akitá LLC takes reasonable measures to protect your data, including:</p>
              <ul className="list-disc pl-6 space-y-2 mt-2">
                <li>Encrypted storage for sensitive information</li>
                <li>Secure transport (HTTPS/TLS)</li>
                <li>Regular security audits and access controls</li>
              </ul>
              <p className="mt-4 text-gray-400 italic">
                However, no system is 100% secure, and we cannot guarantee absolute protection.
              </p>
            </Section>

            <Section number="7" title="Data Rights">
              <p>Depending on your region, you may request:</p>
              <ul className="list-disc pl-6 space-y-2 mt-2">
                <li>Access to your stored data</li>
                <li>Correction of inaccurate information</li>
                <li>Deletion of your personal information</li>
                <li>Revocation of consent for data processing</li>
                <li>Export of your data in a readable format</li>
              </ul>
              <p className="mt-4 font-medium text-white/90">
                Requests can be submitted via our support email.
              </p>
            </Section>

            <Section number="8" title="Event & Business Responsibilities">
              <p>For commercial users (photographers, event planners, businesses):</p>
              <ul className="list-disc pl-6 space-y-2 mt-2">
                <li>You are responsible for informing attendees that their photos may be processed through AI.</li>
                <li>You must comply with applicable privacy, image rights, and data protection laws.</li>
                <li>You must obtain any required consent for capturing or processing images of attendees.</li>
              </ul>
              <p className="mt-4 font-medium text-white/90">
                Akitá LLC is not liable for privacy violations caused by misuse of the platform by event organizers.
              </p>
            </Section>

            <Section number="9" title="Children's Privacy">
              <p>PictureMe is not designed for unsupervised use by minors.</p>
              <p className="mt-2 font-medium text-white/90">
                Parents or guardians must ensure appropriate consent when images of minors are uploaded or captured.
              </p>
            </Section>

            <Section number="10" title="Changes to This Policy">
              <p>We may update this Privacy Policy to reflect changes in our platform, technology, or legal requirements.</p>
              <p className="mt-2">
                The latest version will always be posted on our website, and continued use of the service implies acceptance.
              </p>
            </Section>

            <Section number="11" title="Contact">
              <p>If you have privacy questions, requests, or concerns, you can contact us at:</p>
              <div className="bg-card/50 border border-white/10 rounded-xl p-6 mt-4 backdrop-blur-sm">
                <h3 className="text-white font-bold text-lg mb-2">Akitá LLC</h3>
                <p className="text-gray-300">Email: <a href="mailto:hello@akitapr.com" className="text-purple-400 hover:text-purple-300 transition-colors">hello@akitapr.com</a></p>
                <p className="text-gray-300">Location: Puerto Rico</p>
              </div>
            </Section>
          </div>

          {/* Footer */}
          <div className="pt-12 border-t border-white/10 text-center text-gray-500 text-sm">
            <p>&copy; {new Date().getFullYear()} Akitá LLC. All rights reserved.</p>
          </div>
        </motion.div>
      </main>
    </div>
  );
};

const Section = ({ number, title, children }: { number: string; title: string; children: React.ReactNode }) => (
  <section className="scroll-mt-24" id={`section-${number}`}>
    <h2 className="text-2xl font-bold text-white mb-4 flex items-center gap-3">
      <span className="flex items-center justify-center w-8 h-8 rounded-full bg-white/10 text-sm border border-white/20 shrink-0">
        {number}
      </span>
      {title}
    </h2>
    <div className="pl-11 text-gray-300 leading-relaxed">
      {children}
    </div>
  </section>
);

export default PrivacyPage;

